apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines
  namespace: openstack
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
  namespace: openstack
rules:
- apiGroups: [batch]
  resources: ["*"]
  verbs: [get, list, delete]
- apiGroups: [lcm.mirantis.com]
  resources: [openstackdeployments]
  verbs: [list, get, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: tekton-pipelines

